
apiVersion: v1
kind: ConfigMap
metadata:
  name: bwki-bitfusion-client-configmap
  namespace: bwki
data:
  bitfusion-client-config.yaml: |
    BitfusionClients:

      - BitfusionVersion: "400"
        OSVersion: ubuntu18
        BinaryPath: /bitfusion/bitfusion-client-ubuntu1804_4.0.1-5_amd64.deb/usr/bin/bitfusion
        EnvVariable: /bitfusion/bitfusion-client-ubuntu1804_4.0.1-5_amd64.deb/opt/bitfusion/lib/x86_64-linux-gnu/bitfusion/lib/
        
      - BitfusionVersion: "400"
        OSVersion: ubuntu20
        BinaryPath: /bitfusion/bitfusion-client-ubuntu2004_4.0.1-5_amd64.deb/usr/bin/bitfusion
        EnvVariable: /bitfusion/bitfusion-client-ubuntu2004_4.0.1-5_amd64.deb/opt/bitfusion/lib/x86_64-linux-gnu/bitfusion/lib/
        
      - BitfusionVersion: "400"
        OSVersion: centos7
        BinaryPath: /bitfusion/bitfusion-client-centos7-4.0.1-5.x86_64.rpm/usr/bin/bitfusion
        EnvVariable: /bitfusion/bitfusion-client-centos7-4.0.1-5.x86_64.rpm/opt/bitfusion/lib/x86_64-linux-gnu/bitfusion/lib/
        
      - BitfusionVersion: "400"
        OSVersion: centos8
        BinaryPath: /bitfusion/bitfusion-client-centos8-4.0.1-5.x86_64.rpm/usr/bin/bitfusion
        EnvVariable: /bitfusion/bitfusion-client-centos8-4.0.1-5.x86_64.rpm/opt/bitfusion/lib/x86_64-linux-gnu/bitfusion/lib/
        
